### PR TITLE
Add collect-debug-logs to tinypilot-privileged directory

### PR DESCRIPTION
**Pull request by mtlynch**
Related: https://github.com/mtlynch/tinypilot/issues/426

### CODE REVIEW

**Comment by jotaen** [comment]
@mtlynch Is there a reson why `collect-debug-logs` has different permissions than the other scripts?

```
-rw-r--r--   collect-debug-logs
-rwxr-xr-x   init-usb-gadget
-rwxr-xr-x   update
```

**Comment by mtlynch** [comment]
Good question! No, just a mistake. #91 fixed it.

**Comment by jotaen** [comment]
Also I believe `[-hsu]` in the help text might not be correct?

**Comment by mtlynch** [comment]
>Also I believe [-hsu] in the help text might not be correct?

Oh, good catch! Fixed in #93.

**Pull request merged**
