### PR TITLE
Move init-usb-gadget to this repository

### LINKED ISSUE #67: Move init-usb-gadget to ansible-role-tinypilot
The file `init-usb-gadget` currently lives in the TinyPilot repo:

https://github.com/mtlynch/tinypilot/blob/33d3cd5630ea17c4ce02eb436f0cdf436d72ac0a/scripts/usb-gadget/init-usb-gadget

But there's an elevation of privilege risk here because the file is writable by the unprivileged `tinypilot` user, but it's executed as `root` during startup, so if an attacker compromised `tinypilot`, they'd compromise the whole system.

To remediate this, we should move the `init-usb-gadget` back to this repo and add an Ansible play where it places the file in `/opt/tinypilot-privileged/init-usb-gadget` with mode `700`.

We'll also need to update references to `/opt/tinypilot/scripts/usb-gadget/init-usb-gadget` in both this repo and the tinypilot repo.

### PR DESCRIPTION
**Pull request by tretinha**
The init-usb-gadget script used to live in the TinyPilot repo, now they
live under `scripts/usb-gadget/`.

This fixes #67 security concerns by changing the file mode to 700 and
owner/group to root.

A few changes were made:

1. `tasks/install_usb_gadget.yml` now contains the steps to create the
new `/opt/tinypilot-privileged` directory and populate it with the
`init-usb-gadget` file.
2. `templates/usb-gadget.systemd.j2` now points to the new
`/opt/tinypilot-privileged` location.
3. `defaults/main.yml` received new entries to make the job under
`tasks/install_usb_gadget.yml` easier.

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68)

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @tretinha)

___
*[defaults/main.yml, line 5 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSS5bz7_pE9GtAFgX3:-MQSS5bz7_pE9GtAFgX4:b-joew7v) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/defaults/main.yml#L5)):*
> ```YAML
> tinypilot_user: tinypilot
> tinypilot_dir: /opt/tinypilot
> init_usb_gadget_path: /opt/tinypilot-updater/mtlynch.tinypilot/scripts/usb-gadget/init-usb-gadget
> ```

I'd rather not make assumptions about where the role files will live.

We can create a `files/` directory in this role, place `init-usb-gadget` in the `files/` directory, and then copy it to its final destination with [the `copy` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html).

That's the way the role used to do it:

https://github.com/mtlynch/ansible-role-tinypilot/pull/37/files
___
*[defaults/main.yml, line 6 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSSkrE1H4TyOWEm6e7:-MQSSkrE1H4TyOWEm6e8:bcz35yp) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/defaults/main.yml#L6)):*
> ```YAML
> tinypilot_dir: /opt/tinypilot
> init_usb_gadget_path: /opt/tinypilot-updater/mtlynch.tinypilot/scripts/usb-gadget/init-usb-gadget
> final_init_usb_gadget_path: /opt/tinypilot-privileged/init-usb-gadget
> ```

Can we make `/opt/tinypilot-privileged` its own variable? That way, we don't have to use a magic string in [install_usb_gadget.yml](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/tasks/install_usb_gadget.yml#L28).
___
*[scripts/usb-gadget/README.md, line 3 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSRrFKBrkwDsftKWZH:-MQSRrFKBrkwDsftKWZI:bimpo5d) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/scripts/usb-gadget/README.md#L3)):*
> ```Markdown
> # usb-gadget
> 
> This script runs at Pi's startup (configured in [ansible-role-tinypilot](https://github.com/mtlynch/ansible-role-tinypilot)) and uses the USB OTG port to impersonate a composite USB device.
> ```

We can remove this file since the comment at the top of init-usb-gadget is sufficient.

**Review by tretinha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mtlynch)

___
*[defaults/main.yml, line 5 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSS5bz7_pE9GtAFgX3:-MQSko6594ZCqCwmz8sA:b-8pnuav) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/defaults/main.yml#L5)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I'd rather not make assumptions about where the role files will live.

We can create a `files/` directory in this role, place `init-usb-gadget` in the `files/` directory, and then copy it to its final destination with [the `copy` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html).

That's the way the role used to do it:

https://github.com/mtlynch/ansible-role-tinypilot/pull/37/files
</blockquote></details>

Done. This is indeed much better.
___
*[defaults/main.yml, line 6 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSSkrE1H4TyOWEm6e7:-MQSkqw7Bk5joqKCVoFw:b-896fix) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/defaults/main.yml#L6)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we make `/opt/tinypilot-privileged` its own variable? That way, we don't have to use a magic string in [install_usb_gadget.yml](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/tasks/install_usb_gadget.yml#L28).
</blockquote></details>

Done.
___
*[scripts/usb-gadget/README.md, line 3 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-MQSRrFKBrkwDsftKWZH:-MQSkt1r66OuWxn8MVq1:b-896fix) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/49d2b12be812bf575aa5e27a49a9b07c3e754379/scripts/usb-gadget/README.md#L3)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

We can remove this file since the comment at the top of init-usb-gadget is sufficient.
</blockquote></details>

Done.

**Review by mtlynch — APPROVED** [review]
:lgtm: 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/68#-:-MQTkG1u-6FdtL6MKiyw:b-41s8zb)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mtlynch)

**Comment by mtlynch** [comment]
Whoops this actually caused a break. This repo's test missed it, but TinyPilot caught it:

https://app.circleci.com/pipelines/github/mtlynch/tinypilot/866/workflows/c167a667-6e95-48ad-b653-1cd19d040cea

I fixed it in #69.

The testing gap was because the ansible tests were skipping the tasks related to init-usb-gadget in CI. This was because when I added those tests, I was having trouble getting systemd to run under Docker, but systemd works under the current image, so I removed that workaround in #70, which should catch things like this in the future.

**Comment by tretinha** [comment]
Oh, I'm glad to hear you managed to fix it fast. Damn, the fix was something I was already doing but stopped because `dest` should in theory be able to create the directory if it doesn't exist. I was just skimming through the CI "green" outputs, I should've paid more attention to this. I'm sorry.

**Comment by mtlynch** [comment]
No problem, it was a gap in testing, so the green gave false confidence. Generally, we should be able to trust the tests.

**Pull request merged**
